eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#      下面的配置为什么不管用啊？
#  instance:
#    hostname: testName
spring:
  application:
    name: client
